.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809
    - windows

stages:
  - build

build:
  extends:
    - .shared_windows_runners
  stage: build
  script:
      - docker build --build-arg WIN_VER=${win} --build-arg EDB_VER=${psql} --build-arg PGIS_VER=${pgis} --tag opengisch/postgis-windows:pg${{matrix.psql}}-pgis${{matrix.pgis}}-win${{matrix.win}} .
      - echo ${DOCKER_HUB_ACCESS_TOKEN} | docker login --username ${secrets.DOCKER_HUB_USERNAME} --password-stdin
      - docker push --all-tags opengisch/postgis-windows
  parallel:
    matrix:
      pgis:
        - '10-2.5.3'
      psql:
        - '10.18-2'
      win:
        - '10.0.17763.2183'
        - '1903'
        - '1803'
