on: push
jobs:
  docker-build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        pgis:
          - '10-2.5.3'
        psql:
          - '10.18-2'
        win:
          - '10.0.17763.2183'
          - '1903'
          - '1803'

    steps:
      - uses: actions/checkout@v1

      - name: Build
        run: docker build --build-arg WIN_VER=${{matrix.win}} --build-arg EDB_VER=${{matrix.psql}} --build-arg PGIS_VER=${{matrix.pgis}} --tag opengisch/postgis-windows:pg${{matrix.psql}}-pgis${{matrix.pgis}}-win${{matrix.win}} .

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push
        run: docker push --all-tags opengisch/postgis-windows
